#!/usr/bin/env bash

set -e

apt-get update -y
apt-get upgrade -y
apt-get install -y zsh unzip
snap install chezmoi --classic
chezmoi init --apply https://gitlab.com/sujianqingfeng/dotfiles.git
chsh -s /bin/zsh 
curl -fsSL https://gitlab.com/hens/proxy/raw/main/fnm-install.sh | bash 



