#!/usr/bin/env bash

set -e

apt-get update && apt-get upgrade
apt-get install -y zsh 
chsh -s /bin/zsh 
curl -fsSL https://gitlab.com/hens/proxy/raw/main/fnm-install.sh | bash 
snap install chezmoi --classic
chezmoi init --apply sujianqingfeng



